### ISSUE TITLE
MSI: Azure Functions

### ISSUE THREAD

**Issue by true-while** [mspremier/AzureFastStartForIoT#11]
1. Function creation is confuse me when I get on portal.   http://functions.azure.com/ Description how to get on function create page need to be provided. After several attempts I found that, I need to click on “Login to your account” 
![1](https://cloud.githubusercontent.com/assets/25492227/22528318/c2eede3a-e8a0-11e6-9914-fbcb78b81e02.png)

2. It is not clear what type of the function need to be created. I supposed to select “Data processing”. 
![2](https://cloud.githubusercontent.com/assets/25492227/22528359/f082c23a-e8a0-11e6-9f4d-bd040b07361a.png)

3. No description about what data need to be provided in “Event Hub name”. full name or jus hub’s name.

4. Running functions is actually provide an exception like empty path value. That is normal because there is no data in the event hub but it’s make me waste time on troubleshooting this problem. Please mention this in the description.

**Comment by UKNorthernlad** [comment]
You are seeing this page because you are not logged into the Azure Portal when you click on the http://functions.azure.com/ link. When you are correctly logged-in you are taken to the page shown in the documentation and not as you show above.

I will update the documentation to ensure the user is logged-in.

**Comment by UKNorthernlad** [comment]
Advice to login to the portal before starting trying to create Azure Functions has been added.
